# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://pooyanjamshidi.github.io # the base hostname & protocol for your site

# User settings
title: Pooyan Jamshidi
description: Welcome to my homepage
email: pjamshid@cse.sc.edu
group: AISys Lab
groupweb: https://github.com/softsys4ai
dept: Computing Science and Engineering
deptweb: https://cse.sc.edu/
institution: University of South Carolina
institutionweb: https://www.sc.edu
address: Storey Innovation Center
office: 2207
lab: 2212
twitter: pooyanjamshidi
github: pooyanjamshidi
dblp: Jamshidi:Pooyan
gscholar: Jre2RUQAAAAJ
researchgate: Pooyan_Jamshidi
slideshare: pooyanjamshidi
stackexchange: pjamshidi

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 3
paginate_path: /news/page:num/
excerpt_separator: <!--more-->

# Site-wide variables
keywords: machine learning, artificial intelligence, computer systems, autonomic computing, adversarial machine learning, transfer learning, learning-enabled autonomous systems, representation learning
copyright: Copyright (c) Pooyan Jamshidi

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
#  - jemoji
