# 2020
- name: ICSE
  role: PC Member
  year: 2020
  website: https://conf.researchr.org/home/icse-2020

- name: SEAMS
  role: PC Member
  year: 2020
  website: https://conf.researchr.org/home/seams-2020

- name: ICPE
  role: PC Member
  year: 2020
  website: https://icpe2020.spec.org/

- name: VaMoS
  role: PC Member
  year: 2020
  website: https://vamos2020.dbse.iti.cs.ovgu.de/

- name: ICGSE
  role: PC Member
  year: 2020
  website: https://conf.researchr.org/home/icgse-2020