- name: ECAI
  role: PC Member
  year: 2024
  website: https://www.ecai2024.eu/

- name: ACSOS
  role: Demo & Poster Co-Chair
  year: 2024
  website: https://2024.acsos.org/

- name: ICSE
  role: PC Member
  year: 2024
  website: https://conf.researchr.org/home/icse-2024

- name: SEAMS
  role: PC Co-Chair
  year: 2023
  website: https://conf.researchr.org/home/seams-2023

- name: ICSE/NIER
  role: PC Member
  year: 2022
  website: https://conf.researchr.org/track/icse-2022/icse-2022-nier---new-ideas-and-emerging-results

- name: AutoML
  role: Area Chair
  year: 2022
  website: https://automl.cc/

- name: JSys
  role: Co-founder and Co-editor
  year: 2021
  website: http://jsys.org/

- name: SEAMS
  role: PC Member
  year: 2021
  website: https://conf.researchr.org/home/seams-2021

- name: ICSA
  role: PC Member
  year: 2021
  website: https://icsa-conferences.org/2021/

- name: ICPE
  role: PC Member
  year: 2021
  website: https://icpe2021.spec.org/

- name: AISTATS
  role: Reviewer
  year: 2021
  website: http://aistats.org/ 

# 2020
- name: ICSE
  role: PC Member
  year: 2020
  website: https://conf.researchr.org/home/icse-2020

- name: SEAMS
  role: PC Member
  year: 2020
  website: https://conf.researchr.org/home/seams-2020

- name: ICPE
  role: PC Member
  year: 2020
  website: https://icpe2020.spec.org/

- name: VaMoS
  role: PC Member
  year: 2020
  website: https://vamos2020.dbse.iti.cs.ovgu.de/

- name: ICGSE
  role: PC Member
  year: 2020
  website: https://conf.researchr.org/home/icgse-2020