- name: JSys
  role: Founder and Editor
  year: 2021
  website: http://jsys.org/

- name: SEAMS
  role: PC Member
  year: 2021
  website: https://conf.researchr.org/home/seams-2021

- name: ICSA
  role: PC Member
  year: 2021
  website: https://icsa-conferences.org/2021/

- name: ICPE
  role: PC Member
  year: 2021
  website: https://icpe2021.spec.org/

- name: AISTATS
  role: Reviewer
  year: 2021
  website: http://aistats.org/ 

# 2020
- name: ICSE
  role: PC Member
  year: 2020
  website: https://conf.researchr.org/home/icse-2020

- name: SEAMS
  role: PC Member
  year: 2020
  website: https://conf.researchr.org/home/seams-2020

- name: ICPE
  role: PC Member
  year: 2020
  website: https://icpe2020.spec.org/

- name: VaMoS
  role: PC Member
  year: 2020
  website: https://vamos2020.dbse.iti.cs.ovgu.de/

- name: ICGSE
  role: PC Member
  year: 2020
  website: https://conf.researchr.org/home/icgse-2020